### ISSUE TITLE
Upgrade to 2017.1, Plugin doesn;t work

### ISSUE THREAD

**Issue by ellisd5** [sonar-intellij-plugin/sonar-intellij-plugin#177]
Since upgrading to 2017.1, the plugin no longer works, get this error...

```
com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
java.lang.NoSuchMethodError: com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.isInspectionToolEnabled(SonarQubeInspectionContext.java:86)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:112)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:322)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:394)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:278)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:278)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:137)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by silasg** [comment]
I have exactly the same error.

**Comment by mcmahonjohn** [comment]
How can we find out what changes in 2017.1 is breaking the plugin?

**Comment by mcmahonjohn** [comment]
@omayevskiy Seems like a similar problem that occurred with the upgrade to 2016.3 (#168). The API has changed somewhere.

**Comment by oleynik** [comment]
I fixed compatibility issue and now plugin work with v.2017.1. Please review my pull request - https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/pull/178

**Comment by vandernorth** [comment]
@oleynik great fix! 

For others like me, being inpatient, just change line 122 in
``WebStorm 2017.1\plugins\sonar-intellij-plugin\META-INF\plugin.xml`` to something like 
``<idea-version since-build="163.7743" until-build="180.*"/>``
Credits to @oleynik

**Comment by oleynik** [comment]
@vandernorth, thanks for your feedback. 
I have added compatibility for all versions of this year.
Hope it would help

**Comment by bdbogjoe** [comment]
i wanted to report same issue, nice to see that already fixed, @omayevskiy  when do you plan do release next version ?

**Comment by marsc** [comment]
Would be great to get the new version asap.

**Comment by dagwud** [comment]
Not sure who has to approve/merge the PR raised by @omayevskiy, but in the mean time you can fix locally:

(Note - this works on IntelliJ Ultimate 2017.1.2, but can't see why 2017.1.1 wouldn't be fine too)
* Uninstall existing plugin (via settings > Plugins)
* Restart IntelliJ
* Download zip sonar-intellij-plugin-2.1.1-SNAPSHOT - [here](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/releases/tag/2.1.1-SNAPSHOT)
* Extract the zip
* Edit sonar-intellij-plugin/META-INF/plugin.xml
* Find the <idea-version> tag - line 115 at time of writing
* Change the value of until-build (currently "163.\*") to "179.\*"
* Re-zip the folder
* In IntellJ, Settings > Plugins > Install plugin from disk
* Select the re-zipped file
* Restart IntelliJ

**Comment by Stargator** [comment]
@omayevskiy 2017.2 is available as a EAP, so be mindful that they may get released soon and then this plugin will be listed as not supported.

**Comment by omayevskiy** [comment]
@Stargator this should be hopefully be covered by until-build="179.*"

**Comment by Stargator** [comment]
@omayevskiy I have the 2017.2 update (build 172.3317.76) prompt and it says "Plugin incompatible with new build found: SonarQube Community Plugin"

**Comment by Stargator** [comment]
And it should be noted, in the Terminal I ran IntelliJ from I saw this:

WARN: Can't load PluginDescriptor[name='SonarQube Community Plugin', classpath='/root/.IntelliJIdea2017.1/config/plugins/sonar-intellij-plugin-2.1.2.jar']: until build 171.SNAPSHOT does not match 172.3317.76

**Comment by rkodiyalam** [comment]
I have a similar issue and the same error, any suggestions?

**Comment by dougbacelar** [comment]
IntelliJ is now on version 2017.2 and I can't get this to work.

My configuration looks like the one below(had to cover some info):
![sonar-config](https://user-images.githubusercontent.com/9267678/28828287-30d31dc0-76c8-11e7-8289-7d80f1c596de.PNG)

If I run the script on the command line prompt it works fine(json report is generated correctly).

But when I do Analyze->Inspect Code, SonarQube is not ran at all. I can see that the sonar-report.json is not generated

I am not getting any error messages, just the following:
`No suspicious code found. 193 files processed in 'Project 'project-name''.`

But I can see the project has nearly 300 bugs using the SonarQube's web UI.

I can also see that the SonarQube options are ticked under Settings->Inspection

Am I missing something here? Is this issue fixed by #181 ?

**Comment by mcmahonjohn** [comment]
@dougbacelar @oleynik committed a [new change](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/commit/859d66fc63b666823370dc88d4e8fd3a406e548c). Download the master version of the plugin and build it. Then take the generated jar file and install it as a IntelliJ plugin.

I'm about to do that myself and see if it resolves the issue I saw.

**Comment by oleynik** [comment]
Hi

Yes, I believe that my fix should resolve the problem.
Unfortunately I have some problem with pull request – every time I got an **AssertionError: entry.getValue**. I don't know when I wrong/ what I missed. So please rebuild plugin manually.

**Comment by dougbacelar** [comment]
Thanks for the replies.

I cloned the project, and @oleynik [changes](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/commit/859d66fc63b666823370dc88d4e8fd3a406e548c) weren't on master yet so I manually added them.

Then I tried to generate a jar file but didn't manage to get it to work.

Also tried zipping the project and `installing the plugin from disk` like suggested on [this comment](https://github.com/sonar-intellij-plugin/sonar-intellij-plugin/issues/177#issuecomment-302404078) but got the following error:
`Fail to load plugin descriptor from file sonar-intellij-plugin-master.zip`

Will get back to this when I have more time 👍

**Comment by oleynik** [comment]
@dougbacelar just run **clean** and **build** and than follow to _build/distributions_ directory and pick up _sonar-intellij-plugin-2.1.2-SNAPSHOT.zip_ – this is your plugin. Try to install this ZIP file

**Comment by Stargator** [comment]
@oleynik I currently have IntelliJ 2017.1.5.

I cannot install the plugin generated from your branch because it is incompatible with IntelliJ 2017.1.5.

However, once I upgrade to IntelliJ 2017.2.1, it prompts me to install version 2.1.0 of sonar-intellij-plugin.

So I installed it. Then I decided to go back to your branch and I rebased your branch onto the latest changes in sonar-intellij-plugin's master branch.

Now I have version 2.1.2 installed.

**Comment by oleynik** [comment]
Hi, 
@Stargator, sorry, I didn't get your point. Seems all works as I expect: my branch is compatible only with IntelliJ v.2017.2 and incompatible with v.2017.1.

Could you please provide more details of your issue if it is still relevant?

**Comment by Stargator** [comment]
My point was that the plugin generated from your branch is incompatible with 2017.1.5, but it is compatible with 2017.2.

Additionally, it seems version 2.1.0 of the plugin is already compatible with 2017.2. So I think somewhere, a version of the plugin says it's no longer compatible with 2017.1.5, but works with 2017.2.

So since a version of the plugin already works with 2017.2, from what I saw though it's not definite, your changes may not be needed.

I'll see if I can test that a bit more.

**Comment by omayevskiy** [comment]
plugin works to me for 2017.1 and 2017.2
closing
