### ISSUE TITLE
Does not work with CLion 2018.3 EAP

### ISSUE THREAD

**Issue by halecivo** [sonar-intellij-plugin/sonar-intellij-plugin#210]
When running code inspection:

`java.lang.NoSuchMethodError: com.intellij.codeInspection.ex.GlobalInspectionContextBase.getCurrentProfile()Lcom/intellij/codeInspection/InspectionProfile;
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.isInspectionToolEnabled(SonarQubeInspectionContext.java:86)
	at org.intellij.sonar.analysis.SonarQubeInspectionContext.performPreRunActivities(SonarQubeInspectionContext.java:112)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.initializeTools(GlobalInspectionContextBase.java:312)
	at com.intellij.codeInspection.ex.GlobalInspectionContextImpl.runTools(GlobalInspectionContextImpl.java:384)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.a(GlobalInspectionContextBase.java:274)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase.performInspectionsWithProgress(GlobalInspectionContextBase.java:274)
	at com.intellij.codeInspection.ex.GlobalInspectionContextBase$2.run(GlobalInspectionContextBase.java:229)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:728)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:583)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:533)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:404)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:316)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by icecuber** [comment]
![image](https://user-images.githubusercontent.com/1236294/49089777-8eb5eb00-f25c-11e8-89a3-3f3c03485801.png)

Updating from Intellij CE 2018.2.7 to 2018.3 disable the plugin version 2.5,
On Intellij Ultimate 2018.3 i can install an old 2.1 version from repository but it's not working, 
i can't install from disk the 2.5 version

**Comment by Epithumia** [comment]
This is presumably in need of a similar fix like #206 which fixed #204. Maybe @omayevskiy could get a quick fix in and have it pushed to the ItelliJ repo ?
